### ISSUE TITLE
Bug Report: Deploy Private DNS Zones - Storage Table - Policy deployment missing

### ISSUE THREAD

**Issue by uol-amrae** [Azure/Enterprise-Scale#1502]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Versions

**terraform**: 1.6.3

**azure provider**:  3.80.0

**module**: 5.0.2

#### Describe the bug

Using the connectivity option to create privatelink.table.core.windows.net Private DNS zones and the associated Azure Policy, the 'table' zone is not populated.

seems that the config for 'table' is missing partly from at least:
[modules/connectivity/locals.tf] ( definitions not under Deploy-Private-DNS-Zones ? )

seems that the config for 'table' is missing complete from at least:
[modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_private_dns_zones.tmpl.json]
[modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_private_dns_zones.tmpl.json]

but it is however defined in the audit policy:
[modules/archetypes/lib/policy_definitions/policy_definition_es_audit_privatelinkdnszones.json]

hopefully I've got all that the right way round and explained well enough

#### Steps to Reproduce

Deploy  CAF ES module, configuring Private DNS Zone implementation.
* blob, web, file, queue, dfs, etc. - PDNS Zones created & Policy Definition is created & deployed
* table - PDNS Zone created, but no Policy Definition/Association

locals {
  configure_connectivity_resources = {
    settings = {
      ...
      dns = {
        enabled = true
        config = {
          enable_private_link_by_service = {
            ...
            storage_account_blob       = true
            storage_account_file         = true
            storage_account_queue    = true
            storage_account_table      = true
            ...

**Comment by Springstone** [comment]
This has been resolved in a previous release. Closing as no further action required. Feel free to re-open if needed.

**Comment by mehowq** [comment]
Looking at the latest release v0.19.4 this issue still exists and hasn't been fixed.
