### ISSUE TITLE
Azure Landing Zone Accelerator does not create GitHub CICD actions

### ISSUE THREAD

**Issue by jovadker** [Azure/Enterprise-Scale#911]
**Describe the bug**
Using the Azure Landing Zone Accelerator to deploy the eslz manually, the wizard doesn't create the GitHub repository and GH actions respectively. There is no error message among the deployments, nothing that could be analyzed.

**Steps to reproduce**

1. Start the Landing Zone Accelerator
https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale%2Fmain%2FeslzArm%2Feslz-portal.json
2. Setup GitHub integration by providing organization, new repo name and PAT token
3. Wait for the completion of the wizard

**Screenshots**
![image](https://user-images.githubusercontent.com/24881415/153437376-c09e0cd1-b8fc-474e-acf9-d36b5abd0dab.png)

![image](https://user-images.githubusercontent.com/24881415/153437440-8de7bf86-b41e-4985-845f-3c0a2a0ee577.png)

**Comment by krnese** [comment]
When selecting new Service Principal, did you complete the wizard so that you could provide the secret in the portal UX? Documentation for the setup is @ https://github.com/Azure/Enterprise-Scale/wiki/Deploying-Enterprise-Scale-Platform-DevOps

**Comment by jovadker** [comment]
I have let those settings as they were, because I thought that wizard would create a new SP. I have also created the PA token, but I think with less right than required. Since my org is rolled out in MSFT demo account, I need to authorize my PA token to ESLZ org. I will give another try, because the aforementioned link was not known for me.

**Comment by daltondhcp** [comment]
@jovadker - Let us know when you have tried to redeploy!

**Comment by jovadker** [comment]
I have tested today, I have created a new PAT token, a service principal and I went through the wizard. Now I'm getting the following error message:
![image](https://user-images.githubusercontent.com/24881415/153603817-c73bfd43-be70-4460-a56f-f3fd18209191.png)

**Comment by jtracey93** [comment]
Looks like you found a bug here @jovadker which I will track and fix under #914.

**Comment by jtracey93** [comment]
@jovadker #914 has been fixed and change made and merged. You can test again now creating a new service principal as @krnese suggested above as this issue was unrelated.

**Comment by jovadker** [comment]
Hi, 

it is still not working. I have tried with the following configuration:
![image](https://user-images.githubusercontent.com/24881415/154730471-e854b56d-7912-46ff-a117-0c3065b51be1.png)

The deployment is still running after more than 1,5 hours:

![image](https://user-images.githubusercontent.com/24881415/154730782-6f391a9a-63ec-46c9-b4b8-12c0897285ff.png)

No repository, no action has been created in my org,

What else should I provide you to investigate the issue?

Best regards,
József

**Comment by daltondhcp** [comment]
It looks like you have selected the same subscription, `(Visual Studio Enterprise, ends with 7ba2539216e8)` under Management, Identity and Landing Zones, making the deployment fail with conflicts since a subscription can't exist under multiple management groups. 
<img width="868" alt="image" src="https://user-images.githubusercontent.com/16622613/154811113-bbc9e545-37dd-45ff-a1a2-110221ad1ef7.png">
To resolve the issue, either redeploy with the 'Single' subscription option, or again with 'Dedicated' but skip to add subscriptions under Identity and Landing Zones. 

If you only want to wire up AzOps, you can always do that outside of the portal experience by following the instructions at https://github.com/azure/azops/wiki/github-actions.

**Comment by jovadker** [comment]
OK, I will follow the other tutorial to get an environment that is able to deploy policy changes at tenant or management group level.
